### PR TITLE
public GET and rate-limit

### LINKED ISSUE #3: Webservices public GET and rate-limit
### Steps to reproduce the issue

As for now to execute  a GET endpoint like  `api/index.php/v1/weblinks`  you need to pass an Authorization Token like Bearer or X-Joomla-Token

`curl --location 'https://www.demo.it/api/index.php/v1/weblinks' \
--header 'X-Joomla-Token: c2hhMjU2OjE0MTpjODEzMmE0ZGY3Nzk0YTgzYTk1MTFlNGVhMzVCNAc1ZjhiN2EzY2M3MmM5M2VhMzIzNDdlODdmMmI1NTU0ODVk`

It should be possibile from an admin to allow a GET for public and in this sceanrio implement a rate limit 

### Expected result

as a starting point see https://github.com/joomla-extensions/weblinks/pull/622

full scenario system test

### Actual result

N/A

### PR DESCRIPTION
**Pull request by mahmoudmagdy1-1**
Pull Request for Issue #3  .

### Summary of Changes
Continuation of https://github.com/joomla-extensions/weblinks/pull/622, and added Cypress tests to make sure everything works correctly.

### CODE REVIEW

**Comment by alikon** [comment]
please do this pr to https://github.com/joomla-extensions/weblinks also
thanks in advance

p.s
for still unknown to me reasons drone it's not running on this repo

File: src/api/components/com_weblinks/src/Controller/WeblinksController.php [hunk 1]
```diff
@@ -40,6 +45,143 @@ class WeblinksController extends ApiController
...
+
+    /**
+     * Handles rate limiting with persistent caching.
+     */
+    private function applyPersistentRateLimit(string $userIp, int $maxRequests, int $windowSeconds): void
+    {
+        // Use Joomla cache if persistent
+        $cache = Factory::getContainer()->get(CacheControllerFactoryInterface::class)
+            ->createCacheController('output', [
+                'defaultgroup' => 'api_rate_limit',
```
Comment (alikon) [inline src/api/components/com_weblinks/src/Controller/WeblinksController.php]: wondering if you could find a better name
 it's too generic and maybe it can conflict with other extensions

Comment (mahmoudmagdy1-1) [reply src/api/components/com_weblinks/src/Controller/WeblinksController.php]: how about prefixing with `weblinks` in the start? like `weblinks_api_rate_limit`?

Comment (alikon) [reply src/api/components/com_weblinks/src/Controller/WeblinksController.php]: good one

**Comment by alikon** [comment]
as discussed in the meeting , please do the pr on the main repo

**Comment by alikon** [comment]
thank you
